package com.monarchapis.api.urlshortener.v1.resource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import com.google.common.base.Optional;
import com.monarchapis.api.urlshortener.v1.model.ExpandRequest;
import com.monarchapis.api.urlshortener.v1.model.ItemsResponse;
import com.monarchapis.api.urlshortener.v1.model.ShortenRequest;
import com.monarchapis.api.urlshortener.v1.model.ShortenedUrl;
import com.monarchapis.api.urlshortener.v1.service.UrlShortenerService;
import com.monarchapis.driver.annotation.ApiVersion;
import com.monarchapis.driver.annotation.Authorize;
import com.monarchapis.driver.annotation.Claim;
import com.monarchapis.driver.exception.ForbiddenException;
import com.monarchapis.driver.exception.NotFoundException;
import com.monarchapis.driver.model.Claims;

/**
 * TODO
 * 
 * @title URL Shortener API
 * @version v1
 */
@RestController
@RequestMapping(value = "/v1")
@ApiVersion("1")
public class UrlResource {
	@Autowired
	private UrlShortenerService urlShortenerService;

	/**
	 * Creates a shortened URL if one does not already exist, Otherwise, the
	 * existing URL will be returned.
	 * 
	 * @param longUrl
	 *            The URL to shorten
	 * @return the created or existing shortened URL
	 */
	@Authorize(client = "urls", delegated = "urls")
	@RequestMapping(value = "/urls/shorten", method = RequestMethod.POST)
	public ShortenedUrl shorten(@Validated @RequestBody ShortenRequest request) {
		if (request.getSlug() != null) {
			Claims claims = Claims.current();

			if (!claims.hasValueInClaim("marketing", "group")) {
				throw new ForbiddenException("shortenedUrls");
			}

			return urlShortenerService.shorten(request.getLongUrl(), request.getSlug());
		} else {
			return urlShortenerService.shorten(request.getLongUrl());
		}
	}

	/**
	 * Creates a shortened URL if one does not already exist, Otherwise, the
	 * existing URL will be returned.
	 * 
	 * @param longUrl
	 *            The URL to shorten
	 * @return the created or existing shortened URL
	 */
	@Authorize(client = "urls", delegated = "urls", claims = @Claim(type = "group", value = "marketing"))
	@RequestMapping(value = "/urls/shorten/{slug}", method = RequestMethod.POST)
	public ShortenedUrl assign(@Validated @RequestBody ShortenRequest request, @PathVariable("slug") String slug) {
		return urlShortenerService.shorten(request.getLongUrl(), slug);
	}

	/**
	 * Expands a slug back to the long URL and optionally increases the visit
	 * count by 1.
	 * 
	 * @param slug
	 *            The slug to look up.
	 * @param visit
	 *            Flag that denotes that the visit count should be increased.
	 * @return If found, the shortened URL
	 * @response code = 404 message = "Shortened URL was not found."
	 */
	@Authorize(user = false, client = "urls")
	@RequestMapping(value = "/urls/expand", method = RequestMethod.POST)
	public ShortenedUrl expand(@Validated @RequestBody ExpandRequest request) {
		if (request.isVisit()) {
			urlShortenerService.signalVisit(request.getSlug());
		}

		return require(urlShortenerService.expand(request.getSlug()));
	}

	/**
	 * Retrieves the shortened URLs generated by the requesting user.
	 * 
	 * @return The list of shortened URLs that the user has created.
	 */
	@Authorize(client = "urls", delegated = "urls")
	@RequestMapping(value = "/me/urls", method = RequestMethod.GET)
	public ItemsResponse<ShortenedUrl> myUrls() {
		String userId = Claims.current().getSubject().or("unknown");

		return new ItemsResponse<ShortenedUrl>(urlShortenerService.urlsByUserId(userId));
	}

	private static ShortenedUrl require(Optional<ShortenedUrl> shortenedUrl) {
		if (shortenedUrl.isPresent()) {
			return shortenedUrl.get();
		}

		throw new NotFoundException("shortenedUrls", "Shortened URL");
	}
}
